# config_gpu.yaml
workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-2  # Updated machine type
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: gcr.io/<project-id>/<docker-img>
    env:  # Added environment variables
      - name: WANDB_API_KEY
        value: $WANDB_API_KEY
