workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: europe-west1-docker.pkg.dev/dtumlops-447611/animal-cls/train:latest
        env:
        - name: WANDB_API_KEY
          value: 2ee82ec9afa5930e5376f49d63571b2fcc8cbfe9
