_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.4
            "8":
                - 2
                - 5
            "12": 0.19.4
            "13": darwin-arm64
batch_size:
    value: 10
epochs:
    value: 10
learning_rate:
    value: 0.0004
