#ruff code check
name: Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: set up python   
              uses: actions/setup-python@v5
              with:
                python-version: 3.12
                cache: 'pip'
                cache-dependency-path: setup.py
            - name: install dependencies
              run: |
                python -m pip install ruff
            - name: run ruff
              run: |
                ruff check .
            - name: run format
              run: |
                ruff format .


